version: "3"

services:
  web:
    depends_on:
      - "db"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/project"
    env_file:
      - ".env"
  db:
    image: "postgres:10-alpine"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "9100:5432"
    env_file:
      - ".env"

volumes:
  postgres:
