default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  database: <%= ENV['DATABASE_NAME'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
